name: 'CI: i386: Build all Test'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [created]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-test-all-components:
    name: 'CI: i386: Build all Test'
    runs-on: ubuntu-latest
    env:
      VERSION: unknown
    steps:
      - name: 'Step 1: Install all packages'
        run: |
          sudo apt-get update
          sudo apt-get install -yy build-essential gcc g++ gdb git unzip pax bison flex texinfo unzip
          sudo apt-get install -yy python3-dev libncurses5-dev zlib1g-dev python-dev curl locales
          sudo apt-get install -yy qemu-system-i386
          sudo apt-get clean all
      - name: 'Step 2: Generating locales'
        run: sudo localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
      - name: 'Step 3: Clone the project repository'
        run: git clone https://github.com/maxpoliak/rtems-ec-cli.git .
      - name: 'Step 4: Make preparations'
        run: ./preparations.sh
      - name: 'Step 5: Build cross-tools'
        run: ./build.sh cross
      - name: 'Step 6: Build RTEMS'
        run: ./build.sh rtems
      - name: 'Step 7: Build application'
        run: |
          ./build.sh
          version=$(basename *.tar.gz .tar.gz)
          echo "::set-env name=VERSION::$version"
      - name: 'Step 8: Upload artifact with the result exe image'
        uses: actions/upload-artifact@v2
        with:
          name: '${{ env.VERSION }}-exe-artifact'
          path: ./*.exe
      - name: 'Step 9: Creating a new bootable image'
        run: |
          dd if=/dev/zero of=boot-disk.img bs=512 count=32130
          sudo ./create-boot-image.sh --file boot-disk.img
      - name: 'Step 10: Upload artifact with the QEMU bootable image'
        uses: actions/upload-artifact@v2
        with:
          name: '${{ env.VERSION }}-boot-disk-img-artifact'
          path: boot-disk.img
      - name: 'Step 11: Test the image on QEMU'
        timeout-minutes: 10
        run: |          
          qemu-system-i386 -m 128 -hda boot-disk.img -M q35 -nographic
